# FamQuest Flutter Analysis Options
# Includes lint rules for production-quality code

analyzer:
  errors:
    # Suppress deprecated API warnings (migration planned for future releases)
    deprecated_member_use: ignore

    # Suppress false positives with Freezed JsonKey annotations
    invalid_annotation_target: ignore

    # Suppress unawaited futures (intentional fire-and-forget operations)
    unawaited_futures: ignore

    # Suppress unused fields (reserved for future error display functionality)
    unused_field: ignore

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"

linter:
  rules:
    # Code quality
    - always_declare_return_types
    - annotate_overrides
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_shadowing_type_parameters
    - avoid_types_as_parameter_names
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - curly_braces_in_flow_control_structures
    - empty_catches
    - file_names
    - hash_and_equals
    - implementation_imports
    - missing_whitespace_between_adjacent_strings
    - no_duplicate_case_values
    - null_closures
    - package_names
    - package_prefixed_library_names
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - recursive_getters
    - slash_for_doc_comments
    - type_init_formals
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_const
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_overrides
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - use_function_type_syntax_for_parameters
    - use_rethrow_when_possible
    - valid_regexps
